name: muslim_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  android_alarm_manager_plus: ^4.0.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.0.0-dev.4
  flutter_timezone: ^4.0.0
  http: ^1.2.2
  permission_handler: ^11.3.1
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
